### ISSUE TITLE
Not working with latest HighCharts

### ISSUE THREAD

**Issue by yolandavdvegt** [JoeKuan/Highcharts-Ext-JS-Adapter#2]
I really like this work, but i cant get it to work with the latest highcharts. 

It throws multiple errors and exceptions.
Tried to fix them but I ended up with more errors. would you take a look?
Would really appreciate that!

**Comment by JoeKuan** [comment]
Are you using the ExtJs 3 or ExtJs 4?

Tar up your code and email to me (kuan.joe@gmail.com) and I will have a look.

**Comment by miguelmich** [comment]
I'm using Extjs 3.4 and the graph is shown but it doesn't show the bars fill color.

**Comment by milani** [comment]
I tested with latest highcharts and Sencha Touch 2. It doesn't work. Sencha Touch 2 uses ExtJS 4.

**Comment by JoeKuan** [comment]
I haven't tested it with Sencha Touch 2 but it is part of the plan to get this working with Touch.

**Comment by corotchi** [comment]
Hey Joe, Is it compatible with sencha touch 2  yet or not ? Thanks !

**Comment by JoeKuan** [comment]
Yes, I mainly got it working and there is still a refresh bug but I don't have time to debug it. I am finishing off a book at the moment, then I will release the extension ASAP.
