### ISSUE TITLE
Sencha touch 2.3.0 with highcharts

### ISSUE THREAD

**Issue by pinidbest** [JoeKuan/Highcharts-Ext-JS-Adapter#3]
Hi Joe, 
I am trying to make your samples work on sencha touch 2.3.0.
I need the column sample with embedded data.
Can you supply a workig code for this?

Even with a store with data inside it. this would be greart.

**Comment by JoeKuan** [comment]
standalone.js and standalone.html are added to the mobile directory.

**Comment by pinidbest** [comment]
added to githhub?

**Comment by JoeKuan** [comment]
YES. It's in mobile directory Highcharts_Sencha repository. You have been using the obsolete extension designed for ExtJs 3.

**Comment by pinidbest** [comment]
first of all thanks a lot. very apoeitiated. will this work with touch 2.3?

**Comment by pinidbest** [comment]
Hi Joe,
Thanks for the standalone for mobile - it solved my problem. Actually the
problem Was I wasn't using jquery.
I have another question - is there a way to add  navigator using highcharts
ux for mobile?
Or is there a chance to limit the number of column being seen in the graph
and scroll left/right to them?
